project:
  type: website

website:
  title: "Martin Petr"
  site-url: https://www.martinp.cz
  description: "Website and blog of Martin Petr."

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    fontsize: 1.2em
