project:
  type: website

website:
  title: "Martin Petr"
  site-url: https://bodkan.net
  description: "Website and blog of Martin Petr"
  navbar:
    left:
    - href: index.qmd
      text: Home
    - href: publications.qmd
      text: Publications
    - href: software.qmd
      text: Software
    - href: talks.qmd
      text: Talks
    - href: teaching.qmd
      text: Teaching

format:
  html:
    theme: simplex
    css: styles.css
    toc: true
    fontsize: 1.2em

resources:
  - CNAME
