---
  title: "Student projects"
---

After finishing my PhD, I've not only had the opportunity to mentor students and supervise their projects but I also found great joy in helping young scientists learn how to do research and teach them how to push projects forwards.

**I'm constantly looking forward for new students to work either work on new projects!**

If you'd like to work with me, please don't hesitate to get in touch. I have many ideas ranging from more traditional aDNA population genetics projects, projects focused more to functional biology using archaic and modern human genomes, research software method development, to more unconventional projects involving the emerging large language models (LLM) and their application to wider, non-biological questions.


### **"Archaic human introgression"**

Lecture and exercises for the *Population genetics* course at the University of Copenhagen, February 2024

-   [slides](https://github.com/bodkan/ku-introgression2024/blob/main/2024-02-28%20lecture.pdf) (PDF download)
-   [exercises and scripts](https://github.com/bodkan/ku-introgression2024) (GitHub)

## 2023

### **"_slendr_ simulations"**

Two day workshop at MPI EVA Leipzig, February 2023

-   [slides](https://bodkan.quarto.pub/mpieva-slendr-2023)
-   [handouts](https://bodkan.quarto.pub/mpieva-slendr-2023-onepage/)
-   [source code](https://github.com/bodkan/mpieva-slendr-2023) (GitHub)


### **"Simulations in population genetics"**

Lecture and exercises for the [*Summer course in analysis of high throughput data for population genetics*](http://popgen.dk/popgen23/), University of Copenhagen, August 2023

-   [slides](https://bodkan.quarto.pub/ku-popgen2023/)
-   [handouts](https://bodkan.quarto.pub/ku-popgen2023-onepage/)
-   [source code](https://github.com/bodkan/ku-popgen2023) (GitHub)

## 2022

### **"Simulations in population genetics"**

Lecture and exercises for the [*Summer course in analysis of high throughput data for population genetics*](http://popgen.dk/popgen22/), University of Copenhagen, August 2022

-   [slides](https://bodkan.quarto.pub/ku-popgen2022-simulations-in-population-genetics/)
-   [handouts](https://bodkan.quarto.pub/ku-popgen2022-simulations-in-population-genetics-onepage/)
-   [source code](https://github.com/bodkan/ku-popgen2022) (GitHub)


## 2021

### **"_admixr_ workshop"**

Online workshop for graduate students of _ANTH 895: Methods and Research in Molecular Anthropology I_, Yale University, March 2021

- [slides](https://github.com/bodkan/admixr-workshop/blob/main/slides.pdf) (PDF download)
- [source code and examples](https://github.com/bodkan/admixr-workshop)