---
title: "Courses, lectures, workshops"
---

Here are links to teaching resources for various lectures or workshops I taught over time: slides, RMarkdown or Quarto source files, scripts, exercises.

**Note:** This page is a work-in-progress. I'm currently going through my teaching archive and uploading or linking relevant information here. If a resource you'd like to see is missing, please get in touch! Thanks for understanding.

## 2025

### **"Building intuition into population genetic fundamentals and inference"**

Practical activity session the *Workshop on Population and Speciation Genomics* in Český Krumlov, January 2025

-   [slides and practical exercises](https://github.com/bodkan/cesky-krumlov-2025) (GitHub)

## 2024

### **"Archaic human introgression"**

Lecture and exercises for the *Population genetics* course at the University of Copenhagen, February 2024

-   [slides](https://github.com/bodkan/ku-introgression2024/blob/main/2024-02-28%20lecture.pdf) (PDF download)
-   [exercises and scripts](https://github.com/bodkan/ku-introgression2024) (GitHub)

## 2023

### **"_slendr_ simulations"**

Two day workshop at MPI EVA Leipzig, February 2023

-   [source code, slides, exercises](https://github.com/bodkan/mpieva-slendr-2023) (GitHub)


### **"Simulations in population genetics"**

Lecture and exercises for the [*Summer course in analysis of high throughput data for population genetics*](http://popgen.dk/popgen23/), University of Copenhagen, August 2023

-   [source code, slides, exercises](https://github.com/bodkan/ku-popgen2023) (GitHub)

## 2022

### **"Simulations in population genetics"**

Lecture and exercises for the [*Summer course in analysis of high throughput data for population genetics*](http://popgen.dk/popgen22/), University of Copenhagen, August 2022

-   [source code, slides, exercises](https://github.com/bodkan/ku-popgen2022) (GitHub)


## 2021

### **"_admixr_ workshop"**

Online workshop for graduate students of _ANTH 895: Methods and Research in Molecular Anthropology I_, Yale University, March 2021

- [slides](https://github.com/bodkan/admixr-workshop/blob/main/slides.pdf) (PDF download)
- [source code and examples](https://github.com/bodkan/admixr-workshop)
